import { financeRow } from "@/src/type/chart";
import { financeFrequency } from "@/src/type/chart";

export const example: financeRow[] = [
  { dateRange: "Jan", financeType: "in", total: 1200 },
  { dateRange: "Jan", financeType: "out", total: 450 },
  { dateRange: "Feb", financeType: "in", total: 950 },
  { dateRange: "Feb", financeType: "out", total: 300 },
  { dateRange: "Mar", financeType: "in", total: 1500 },
  { dateRange: "Mar", financeType: "out", total: 600 },
  { dateRange: "Apr", financeType: "in", total: 1100 },
  { dateRange: "Apr", financeType: "out", total: 400 },
  { dateRange: "May", financeType: "in", total: 1350 },
  { dateRange: "May", financeType: "out", total: 750 },
  { dateRange: "Jun", financeType: "in", total: 1600 },
  { dateRange: "Jun", financeType: "out", total: 500 },
  { dateRange: "Jul", financeType: "in", total: 100 },
  { dateRange: "Jul", financeType: "in", total: 850 },
  { dateRange: "Jul", financeType: "out", total: 620 },
  { dateRange: "Aug", financeType: "in", total: 1400 },
  { dateRange: "Aug", financeType: "out", total: 550 },
  { dateRange: "Sep", financeType: "in", total: 1250 },
  { dateRange: "Sep", financeType: "out", total: 480 },
  { dateRange: "Oct", financeType: "in", total: 1900 },
  { dateRange: "Oct", financeType: "out", total: 800 },
  { dateRange: "Nov", financeType: "in", total: 1750 },
  { dateRange: "Nov", financeType: "out", total: 900 },
  { dateRange: "Dec", financeType: "in", total: 2200 },
  { dateRange: "Dec", financeType: "out", total: 1100 },
];

export const financeExample: readonly financeFrequency[] = [
  { type: "GROCERY", frequency: 0.095 },
  { type: "HOUSE", frequency: 0.065 },
  { type: "TRANSPORTATION", frequency: 0.045 },
  { type: "PERSONAL", frequency: 0.028 },
  { type: "MISC", frequency: 0.01 },
  { type: "GROCERY", frequency: 0.085 },
  { type: "HOUSE", frequency: 0.058 },
  { type: "TRANSPORTATION", frequency: 0.04 },
  { type: "PERSONAL", frequency: 0.022 },
  { type: "MISC", frequency: 0.009 },
  { type: "GROCERY", frequency: 0.08 },
  { type: "HOUSE", frequency: 0.052 },
  { type: "TRANSPORTATION", frequency: 0.038 },
  { type: "PERSONAL", frequency: 0.02 },
  { type: "MISC", frequency: 0.008 },
  { type: "GROCERY", frequency: 0.075 },
  { type: "HOUSE", frequency: 0.05 },
  { type: "TRANSPORTATION", frequency: 0.035 },
  { type: "PERSONAL", frequency: 0.018 },
  { type: "MISC", frequency: 0.007 },
  { type: "GROCERY", frequency: 0.065 },
  { type: "HOUSE", frequency: 0.045 },
  { type: "TRANSPORTATION", frequency: 0.032 },
  { type: "PERSONAL", frequency: 0.012 },
  { type: "MISC", frequency: 0.006 },
];
